### ISSUE TITLE
Configuration > Data Model 2/2

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#83]
**TODO**
- [ ] Set page structure for Fields' sub-nested menus.
- [ ] Approval from Ben + Rijk
- [ ] field-types
- [ ] Schema
- [ ] Translations
- [ ] Relationship
- [ ] Field
- [ ] Interface
- [ ] Display
- [ ] Validation
- [ ] Conditions
- [ ] Add Media
- [ ] Proofedit 1
- [ ] Submit for editorial review
- [ ] Final Proofedit
